/*
  ============================================================================
  PROPRIETÁRIO: Maurício Spark
  MARCA: Spark
  PROJETO: Core Icons Library
  VERSÃO: 1.0.0
  LINHAGEM: SPARK
  ============================================================================
  Documento de Planejamento de Escopo
  COPYRIGHT: © 2026 / Maurício Spark.
  ============================================================================
*/

var coreIconsData = (function () {
  var FILES = `abc.png
actionscript.png
ada.png
adonis.png
advplformatter.png
advplinclude.png
advplptm.png
advpltlpp.png
android.png
angular.png
angularcomponent.png
angulardirective.png
angularguard.png
angularpipe.png
angularresolver.png
angularservice.png
apachevelocity.png
apiblueprint.png
apollo.png
applescript.png
appveyor.png
architecture.png
arduino.png
asciidoc.png
assembly.png
astro.png
astyle.png
audio.png
aurelia.png
authors.png
autohotkey.png
autoit.png
aws.png
azure.png
azurepipelines.png
babel.png
ballerina.png
bazel.png
bicep.png
bitbucket.png
blink.png
blitz.png
bootstrap.png
bower.png
brainfuck.png
browserslist.png
buck.png
bucklescript.png
buildkite.png
c.png
c++.png
cabal.png
cake.png
capacitor.png
carbon.png
certificate.png
changelog.png
chess.png
circleci.png
clojure.png
cloudfoundry.png
cmake.png
coala.png
cobol.png
coconut.png
codeclimate.png
codecov.png
codeowners.png
coffeescript.png
coldfusion.png
command.png
commitlint.png
conduct.png
console.png
contributing.png
credits.png
crystal.png
csharp.png
css.png
cssmap.png
cudo.png
cursor.png
cypress.png
d.png
dart.png
dartgenerated.png
database.png
delphidevelopers.png
denizenscripts.png
dependabot.png
dhall.png
diff.png
dinophp.png
disco.png
django.png
docker.png
document.png
dotjs.png
drawio.png
droneci.png
dronemonitor.png
dronestatus.png
duna.png
edge.png
editorconfig.png
ejs.png
elixirls.png
elm.png
email.png
ember.png
erlang.png
eslint.png
exe.png
fastlane.png
favicon.png
fibraoptica.png
figma.png
firebase.png
flash.png
flowlanguage.png
font.png
forth.png
fortran.png
foundation.png
foxpro.png
fsharp.png
fusebox.png
gatsby.png
gcp.png
gemfile.png
gemini.png
git.png
github.png
gitlab.png
gitpod.png
gleam.png
go.png
gobotassets.png
godot.png
gogopher.png
gomod.png
gradle.png
grain.png
graphcool.png
graphql.png
gridsome.png
groovy.png
grunt.png
guj.png
gulp.png
h.png
h++.png
hack.png
handlebars.png
hardhat.png
hashicorphcl.png
haskell.png
haxe.png
helm.png
heroku.png
hexadecimal.png
horuseccli.png
html.png
html6.png
husky.png
idris.png
imba.png
ionic.png
istanbul.png
jarviewer.png
java.png
javaclass.png
javascript.png
javascriptmap.png
jenkins.png
jest.png
jinja.png
jsconfig.png
json.png
julia.png
jupyter.png
jython.png
karma.png
key.png
kotlin.png
lerna.png
less.png
lib.png
lighthouse.png
lilypond.png
liquid.png
lisp.png
liveScript.png
lock.png
lolcode.png
lowcode.png
lua.png
makefile.png
markdown.png
marko.png
mathematica.png
matlab.png
maven.png
mdx.png
merlin.png
meson.png
mirrorImageagency.jpg
mocha.png
modernizr.png
moonscript.png
mustache.png
nest.png
nestcontroller.png
nestdecorator.png
nestfilter.png
nestgateway.png
nestguard.png
nestmiddleware.png
nestmodule.png
nestpipe.png
nestresolver.png
nestservice.png
netlify.png
nextjs.png
nginx.png
ngrxactions.png
ngrxeffects.png
ngrxentity.png
ngrxreducer.png
ngrxselectors.png
ngrxstate.png
nimlanguage.png
nixos.png
nodejs.png
nodejssnippets .png
nodemon.png
python.png
pythonmisc.png
qsharp.png
quasar.png
r.png
racket.png
raml.png
razor.png
react.png
reactnative.png
reactts.png
readme.png
reason.png
red.png
redux.png
reduxaction.png
reduxreducer.png
reduxselector.png
reduxstore.png
remix.png
renovate.png
replit.png
rescript.png
restql.png
riotgames.png
roadmap.png
robot.png
robots.png
rollup.png
rome.png
routergenerator.png
rubocop.png
ruby.png
rust.png
salesforce.png
san.png
sas.png
sass.png
sbt.png
scala.png
scheme.png
search.png
semanticrelease.png
sentry.png
sequelize.png
serverless.png
shader.png
shaderlab.png
silverstripe.png
siyuan .png
sketch.png
slim.png
slug.png
smarty.png
sml.png
snowpack.png
snyk.png
solidity .png
steadybit.png
stencil.png
stitches.png
storybook.png
stryker.png
stylus .png
sublimetext.png
svelte.png
svgo.png
swift.png
tableformatter.png
tailwindcss.png
tauri.png
tcl.png
teal.png
template.png
terraform.png
test js.png
testjs.png
testjsx.png
testts.png
tex.png
textlint.png
tilt.png
tobi.png
tor.png
travis.png
tsconfig.png
tune.png
typescript.png
typescriptimporter.png
uml.png
vagrant.png
vala.png
velocidade.png
vercel.png
verdaccio.png
verilog.png
vim.png
visualstudiocode.png
vite.png
vlang.png
vue.png
vuestore.png
waforth.png
wakatime.png
wallaby.png
watchman.png
webassembly.png
webhintio.png
webpack.png
wepy.png
windicss.png
wolfram.png
xaml.png
xampp.png
yaml.png
yarn.png
zig.png
`.trim().split(/\r?\n/).filter(function (f) { return f.length > 0; });

  function slugFromFile(file) {
    var base = file.replace(/\.[^.]+$/i, "").trim();
    if (/^c\+\+$/i.test(base)) return "c++";
    if (/^h\+\+$/i.test(base)) return "h++";
    var s = base.toLowerCase().replace(/\s+/g, "-");
    s = s.replace(/[^a-z0-9+\-]/g, "-");
    s = s.replace(/-+/g, "-").replace(/^-|-$/g, "");
    return s || "icon";
  }

  var seen = Object.create(null);
  return FILES.map(function (file, i) {
    var name = slugFromFile(file);
    var orig = name;
    var n = 2;
    while (seen[name]) {
      name = orig + "-" + n;
      n++;
    }
    seen[name] = true;
    return { name: name, file: file };
  });
})();